# Generated by Django 3.1.8 on 2021-04-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('count_of_lc', models.IntegerField(verbose_name='Count of lectures')),
                ('date_start', models.DateField(verbose_name='Date of start')),
                ('date_end', models.DateField(verbose_name='Date of end')),
            ],
            options={
                'verbose_name': 'Courses',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
